name: plus_locate
description: generate, decode and locate Google Plus Codes

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  intl: any
  dio: ^5.4.0
  go_router: ^17.0.1
  infinite_scroll_pagination: ^4.0.0
  collection: ^1.18.0
  http: ^1.2.2
  google_fonts: ^8.0.0
  flutter_native_splash: ^2.4.4
  intl_phone_field: ^3.2.0
  flutter_secure_storage: ^9.2.4
  app_theme_kit: ^0.1.0
  web: ^1.1.1
  google_maps_flutter: ^2.12.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^13.0.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  open_location_code: ^1.0.1
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^4.0.2
  json_serializable: ^6.10.0
  source_gen: ^4.3.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

fluttergen:
  output: lib/src/generated
  line_length: 120

  integrations:
    flutter_svg: true
